spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ldes-server
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
ldes:
  dcat: "https://private-api.gipod.vlaanderen.be/api/v1/ldes/mobility-hindrances?generatedAtTime=2021-01-06T18:04:12.173Z"
  hostname: "http://localhost:8080"
  collectionname: "mobility-hindrances"
  validation:
    shape: "https://private-api.gipod.test-vlaanderen.be/api/v1/ldes/mobility-hindrances/shape"
  membertype: "https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder"
  timestamp-path: "http://www.w3.org/ns/prov#generatedAtTime"
views:
  - name: "by-five"
    fragmentations:
      #  - name: "geospatial"
      #    config:
      #      maxZoomLevel: 13
      #      fragmenterProperty: "http://www.opengis.net/ont/geosparql#asWKT"
      - name: "timebased"
        config:
          memberLimit: 5
  - name: "by-ten"
management:
  metrics:
    mongo:
      command:
        enabled: false