name: Make sure new PRs are sent to development

on:
  pull_request_target: # Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ before using
    types: [opened, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: Vankka/pr-target-branch-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: main
          exclude: "develop /hotfix\/+/" # Don't prevent develop and hotfixes from going to main
          change-to: develop
          comment: |
            Your PR was set to target `main`, PRs should be target `develop`
            The base branch of this PR has been automatically changed to `develop`, please check that there are no merge conflicts