name: 3. Build, Deploy and Release Project

on:
  workflow_dispatch:
    inputs:
      type_of_bump:
        type: choice
        description: Type of version bump
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "Maven Release"
          git-release-bot-email: "maven@release.io"
          version-patch: ${{ github.event.inputs.type_of_bump == 'patch' }}
          version-minor: ${{ github.event.inputs.type_of_bump == 'minor' }}
          version-major: ${{ github.event.inputs.type_of_bump == 'major' }}
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true -Dskipdeploy=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          release-branch-name: 'develop'